services:
  app:
    image: registry.big.wtf/mediaserver/backend:development
    build:
      context: .
      target: development
    env_file: .env
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "13000:3000"
    volumes:
      - .:/rails
    deploy:
      replicas: 1
    depends_on:
      - postgresql

  worker:
    image: registry.big.wtf/mediaserver/backend:development
    env_file: .env
    command: bundle exec rails solid_queue:start
    volumes:
      - .:/rails
    deploy:
      replicas: 4
    depends_on:
      - postgresql

  postgresql:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data
    ports:
      - "15432:5432"
    volumes:
      - postgresql:/data
    deploy:
      replicas: 1

volumes:
  postgresql:
