services:
  app:
    image: registry.big.wtf/mediaserver/backend:development
    build:
      context: .
      target: development
    env_file: .env
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "13000:3000"
    volumes:
      - .:/rails
    deploy:
      replicas: 1
    depends_on:
      - postgresql
      - redis

  worker:
    image: registry.big.wtf/mediaserver/backend:development
    env_file: .env
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
    deploy:
      replicas: 4
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data
    ports:
      - "15432:5432"
    volumes:
      - postgresql:/data
    deploy:
      replicas: 1

  redis:
    image: redis:8
    command: --save 60 1 --loglevel warning
    ports:
      - "16379:6379"
    volumes:
      - redis:/data
    deploy:
      replicas: 1

volumes:
  postgresql:
  redis:
