services:
  app:
    image: registry.big.wtf/mediaserver/backend:production
    build:
      context: .
      target: production
    env_file: .env
    ports:
      - "13000:80"
    deploy:
      replicas: 1

  worker:
    image: registry.big.wtf/mediaserver/backend:production
    env_file: .env
    command: bundle exec sidekiq -C config/myapp_sidekiq.yml
    deploy:
      replicas: 1

volumes:
  postgresql:
