default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

development:
  primary: &primary_development
    <<: *default
    database: backend_development
  cache:
    <<: *primary_development
    database: backend_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: backend_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: backend_test

production:
  primary: &primary_production
    <<: *default
    database: backend_production
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
