default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

development:
  <<: *default
  database: mediaserver_development

test:
  <<: *default
  database: mediaserver_test

production:
  <<: *default
  database: mediaserver_production
