name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: cd-main
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: [self-hosted, linux, arm64]
    steps:
      -
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/mediaserver/backend:production-buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/mediaserver/backend:production-buildcache,mode=max
          platforms: linux/arm64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/mediaserver/backend:production

  update:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: [self-hosted, linux, arm64]
    needs: build
    steps:
      -
        name: Send update request to server
        env:
          DEPLOYMENT_UPDATE_URL: ${{ vars.DEPLOYMENT_UPDATE_URL }}
        run: |
          curl -X POST "$DEPLOYMENT_UPDATE_URL"
